apiVersion: v1
kind: Namespace
metadata:
    name: project-a
    labels: 
      namespace: project-a
---
apiVersion: v1
kind: Namespace
metadata:
    name: project-b
    labels: 
      namespace: project-b
---
apiVersion: v1
kind: Namespace
metadata:
    name: project-c
    labels: 
      namespace: project-c
---
#https://github.com/kubernetesway/CKA-Series/tree/main/31-b (edited)
apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  namespace: project-a
  labels:
    app: db-pod
spec:
  containers:
  - name: db-pod
    image: mysql:5.7  # You can specify a different MySQL version if needed
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "YourStrong@Passw0rd"  # Replace with your root password
    - name: MYSQL_DATABASE
      value: "exampledb"  # Replace with your desired database name
    - name: MYSQL_USER
      value: "user"
    - name: MYSQL_PASSWORD
      value: "userpassword"  # Replace with your desired user password
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: service-pod
  namespace: project-b
  labels:
    app: service-pod
spec:
  containers:
  - name: service-pod
    image: kubernetesway/service:v1
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: project-b
  labels:
    app: web-pod
spec:
  containers:
  - name: web-pod
    image: kubernetesway/web:v1
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: application-pod
  namespace: project-c
  labels:
    app: application-pod
spec:
  containers:
  - name: application-pod
    image: kubernetesway/service:v1
    ports:
    - containerPort: 8080
