apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: web-pod
    image: nginx:latest    
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /var/log/nginx
      name: hostpath-volume
  volumes:
  - hostPath:
      path: /var/volume
    name: hostpath-volume
