#https://github.com/kubernetesway/CKA-Series/tree/main/29
apiVersion: v1
kind: Pod
metadata:
  name: application
  labels:
    app: service
spec:
  containers:
  - name: application
    image: kubernetesway/web:v1
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: service
  labels:
    app: service
spec:
  containers:
  - name: service
    image: kubernetesway/service:v1
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
  - name: db
    image: mysql:5.7  # You can specify a different MySQL version if needed
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "YourStrong@Passw0rd"  # Replace with your root password
    - name: MYSQL_DATABASE
      value: "exampledb"  # Replace with your desired database name
    - name: MYSQL_USER
      value: "user"
    - name: MYSQL_PASSWORD
      value: "userpassword"  # Replace with your desired user password
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: web
    image: kubernetesway/web:v1
    ports:
    - containerPort: 80