apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: web-pod
    image: nginx:latest    
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /var/log/nginx
      name: hostpath-volume
  - name: sidecar
    image: busybox:1.28
    command: ['sh', '-c', 'tail -f /var/busybox/log/*.log']
    volumeMounts:
    - mountPath: /var/busybox/log
      name: hostpath-volume
  volumes:
  - hostPath:
      path: /var/volume
    name: hostpath-volume
