apiVersion: v1
kind: Pod
metadata:
  name: my-busybox
spec:
  nodeName: node01 # even if SchedulindDisabled on node01, with this spec it will be scheduled on node01(KillCodda v1.29) ??
  containers:
  - name: c-my-busybox
    image: busybox:1.31.1
    command: ['sh', '-c', 'sleep 4800']
    ports:
    - containerPort: 80